name: envision
description: "A high-fidelity OS algorithm simulator."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  toggle_switch: ^2.3.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icons/icon.png"
  macos:
    generate: true
    image_path: "assets/icons/icon.png"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
